version: "3.2"

services:
  mysql:
    image: mysql:5.7
    env_file:
      - env/.env.dev
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/.env.dev
    volumes:
      - .:/app
      - static_data:/srv
    depends_on:
      - mysql
    expose:
      - 8000

  nginx:
    build: ./config/nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./mysql_data:/var/lib/mysql
      - static_data:/srv:ro  # ro readonly
volumes:
  mysql_data:
  static_data:
