branch-defaults:
  master:
    environment: book-rental-dev
    group_suffix: null
environment-defaults:
  book-rental-dev:
    branch: null
    repository: null
global:
  application_name: book-rental
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
