# Generated by Django 2.2.13 on 2020-06-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrentedbook',
            old_name='fine_applied',
            new_name='fine_charged',
        ),
        migrations.RenameField(
            model_name='rentedbook',
            old_name='fine_applied',
            new_name='fine_charged',
        ),
        migrations.RemoveField(
            model_name='historicalrentedbook',
            name='per_day_charge',
        ),
        migrations.RemoveField(
            model_name='rentedbook',
            name='per_day_charge',
        ),
        migrations.AddField(
            model_name='category',
            name='per_day_charge',
            field=models.FloatField(default=1.0, help_text='Per day charge for the book of this categorydefault is Rs. 1.0 per day for all the categoryCan be changed for individual category'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='per_day_charge',
            field=models.FloatField(default=1.0, help_text='Per day charge for the book of this categorydefault is Rs. 1.0 per day for all the categoryCan be changed for individual category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('regular', 'Regular'), ('fiction', 'Fiction'), ('novels', 'Novels')], default='regular', help_text='Name of the Category', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='name',
            field=models.CharField(choices=[('regular', 'Regular'), ('fiction', 'Fiction'), ('novels', 'Novels')], default='regular', help_text='Name of the Category', max_length=50),
        ),
    ]
