# Generated by Django 2.2.13 on 2020-06-18 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_rental', '0002_auto_20200618_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='per_day_charge',
        ),
        migrations.RemoveField(
            model_name='historicalcategory',
            name='per_day_charge',
        ),
        migrations.CreateModel(
            name='HistoricalCategoryDayCharge',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Time at which object was created')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Time at which object was updated', null=True)),
                ('days_from', models.IntegerField(default=0, help_text='From this number of day per_day_charge starts')),
                ('days_to', models.IntegerField(blank=True, help_text='Till this number of day per_day_charge will be applied', null=True)),
                ('per_day_charge', models.FloatField(default=1.0, help_text='Per day charge for the book of this categorydefault is Rs. 1.0 per day for all the categoryCan be changed for individual category')),
                ('min_charge', models.FloatField(default=0, help_text='Minimum charges are considered when number of days are less than min_days')),
                ('min_days', models.IntegerField(blank=True, help_text='Minimum days to apply min_charges', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, help_text='Category for which this charge is applied', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='book_rental.Category')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who updated the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical category day charge',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryDayCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time at which object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time at which object was updated', null=True)),
                ('days_from', models.IntegerField(default=0, help_text='From this number of day per_day_charge starts')),
                ('days_to', models.IntegerField(blank=True, help_text='Till this number of day per_day_charge will be applied', null=True)),
                ('per_day_charge', models.FloatField(default=1.0, help_text='Per day charge for the book of this categorydefault is Rs. 1.0 per day for all the categoryCan be changed for individual category')),
                ('min_charge', models.FloatField(default=0, help_text='Minimum charges are considered when number of days are less than min_days')),
                ('min_days', models.IntegerField(blank=True, help_text='Minimum days to apply min_charges', null=True)),
                ('category', models.ForeignKey(help_text='Category for which this charge is applied', on_delete=django.db.models.deletion.PROTECT, related_name='dayswise_charges', to='book_rental.Category')),
                ('created_by', models.ForeignKey(help_text='User who created the object', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='User who updated the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('category', 'days_from')},
            },
        ),
    ]
